CREATE TABLE usuarios(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(200) NOT NULL,
	apelido VARCHAR(100),
	sexo VARCHAR(30) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;