CREATE TABLE locais(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	logradouro VARCHAR(200),
	bairro VARCHAR(100),
	cidade VARCHAR(100) NOT NULL,
	estado VARCHAR(100) NOT NULL,
	nome VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;