CREATE TABLE eventos(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	criador_id BIGINT(20),
	local_id BIGINT(20),
	preco DOUBLE PRECISION,
	atracoes VARCHAR(200),
	datahora TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;